
"openapi": "3.1.0"
"info":
  "title": "Bookstore API"
  "description": "CRUD operations for managing books in a bookstore"
  "version": "1.0.0"
"servers":
  -
    "url": "https://bookstore.example.com/api/v1"
"tags":
  -
    "name": "book"
    "description": "Operations about books"
"paths":
  "/books":
    "get":
      "tags":
        - "book"
      "summary": "Get all books"
      "operationId": "getAllBooks"
      "responses":
        "200":
          "description": "A list of books"
          "content":
            "application/json":
              "schema":
                "type": "array"
                "items":
                  "type": "object"
                  "properties":
                    "id":
                      "type": "integer"
                      "format": "int64"
                    "name":
                      "type": "string"
                      "maxLength": 100
                    "author":
                      "type": "string"
                      "maxLength": 50
                  "required":
                    - "name"
                    - "author"
    "post":
      "tags":
        - "book"
      "summary": "Add a new book"
      "operationId": "addBook"
      "requestBody":
        "description": "Book object to be added"
        "required": true
        "content":
          "application/json":
            "schema":
              "type": "object"
              "properties":
                "id":
                  "type": "integer"
                  "format": "int64"
                "name":
                  "type": "string"
                  "maxLength": 100
                "author":
                  "type": "string"
                  "maxLength": 50
              "required":
                - "name"
                - "author"
      "responses":
        "201":
          "description": "Book created successfully"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "id":
                    "type": "integer"
                    "format": "int64"
                  "name":
                    "type": "string"
                    "maxLength": 100
                  "author":
                    "type": "string"
                    "maxLength": 50
                "required":
                  - "name"
                  - "author"
  "/books/{id}":
    "get":
      "tags":
        - "book"
      "summary": "Get a book by ID"
      "operationId": "getBookById"
      "parameters":
        -
          "name": "id"
          "in": "path"
          "description": "ID of the book to retrieve"
          "required": true
          "schema":
            "type": "integer"
      "responses":
        "200":
          "description": "A book object"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "id":
                    "type": "integer"
                    "format": "int64"
                  "name":
                    "type": "string"
                    "maxLength": 100
                  "author":
                    "type": "string"
                    "maxLength": 50
                "required":
                  - "name"
                  - "author"
        "404":
          "description": "Book not found"
    "put":
      "tags":
        - "book"
      "summary": "Update a book"
      "operationId": "updateBook"
      "parameters":
        -
          "name": "id"
          "in": "path"
          "description": "ID of the book to update"
          "required": true
          "schema":
            "type": "integer"
      "requestBody":
        "description": "Book object to be updated"
        "required": true
        "content":
          "application/json":
            "schema":
              "type": "object"
              "properties":
                "id":
                  "type": "integer"
                  "format": "int64"
                "name":
                  "type": "string"
                  "maxLength": 100
                "author":
                  "type": "string"
                  "maxLength": 50
              "required":
                - "name"
                - "author"
      "responses":
        "200":
          "description": "Book updated successfully"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "id":
                    "type": "integer"
                    "format": "int64"
                  "name":
                    "type": "string"
                    "maxLength": 100
                  "author":
                    "type": "string"
                    "maxLength": 50
                "required":
                  - "name"
                  - "author"
        "404":
          "description": "Book not found"
    "delete":
      "tags":
        - "book"
      "summary": "Delete a book"
      "operationId": "deleteBook"
      "parameters":
        -
          "name": "id"
          "in": "path"
          "description": "ID of the book to delete"
          "required": true
          "schema":
            "type": "integer"
      "responses":
        "204":
          "description": "Book deleted successfully"
        "404":
          "description": "Book not found"
"components":
  "schemas":
    "Book":
      "type": "object"
      "properties":
        "id":
          "type": "integer"
          "format": "int64"
        "name":
          "type": "string"
          "maxLength": 100
        "author":
          "type": "string"
          "maxLength": 50
      "required":
        - "name"
        - "author"